### ISSUE TITLE
Multiplication of any number of matrices.

### ISSUE THREAD

**Issue by Tushar11Raj** [amritansh22/Data-Structures-and-Algorithms-in-cpp#104]
### Multiplication of any number of matrices.
**Descpription**
Multiplication of n number of matrices where n is a user input variable.
**Language**
 C++
**Task Details**
Clear Code easy to understand
Proper comments

@amritansh22 Can I work on this?

**Comment by amritansh22** [comment]
@Tushar11Raj Sure. I have assigned the issue to you.

**Comment by Tushar11Raj** [comment]
@amritansh22 I would like to contribute to it as a part of Hacktoberfest.

**Comment by amritansh22** [comment]
@Tushar11Raj Sure
