### ISSUE TITLE
Find frequency of a character in a .txt file

### ISSUE THREAD

**Issue by Tushar11Raj** [amritansh22/Data-Structures-and-Algorithms-in-cpp#105]
### Find frequency of a characters and words in a .txt file

**Desc**
frequency of user input character
frequency of words
frequency of all characters using switch case

**Language**
C++

**Issue**
Create a rasterized program
Proper comments

@amritansh22 Can I do this?

**Comment by amritansh22** [comment]
@Tushar11Raj Sure. I have assigned the issue to you.

**Comment by Tushar11Raj** [comment]
I would like to contribute to it as a part of Hacktoberfest.

**Comment by amritansh22** [comment]
@Tushar11Raj Sure

**Comment by Pratap2018** [comment]
assign me please

**Comment by amritansh22** [comment]
@Pratap2018 This issue is already assigned. You may look for other issues or open your own here.
