### ISSUE TITLE
Convert to sparse matrix

### ISSUE THREAD

**Issue by Tushar11Raj** [amritansh22/Data-Structures-and-Algorithms-in-cpp#106]
### Convert a matrix to its sparse matrix form

**Desc**
Convert a user defined matrix to its sparse form

**Language**
C++

**Issue**
Rasterized Program
Proper comments

@amritansh22  Can I work on this?

**Comment by amritansh22** [comment]
@Tushar11Raj Sure. I have assigned the issue to you.

**Comment by Tushar11Raj** [comment]
@amritansh22 I would like to contribute to it as a part of Hacktoberfest.

**Comment by amritansh22** [comment]
@Tushar11Raj Sure

**Comment by sanyasinghh25** [comment]
Can I contribute to this?

**Comment by amritansh22** [comment]
@sanyasinghh25 Yes sure
