### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by tauseefmohammed2** [amritansh22/Data-Structures-and-Algorithms-in-cpp#107]
### **Binary Search Tree**

- Implementation of Binary Search Tree
- Insertion, Deleting and Searching Elements in a Binary Search Tree

**Type of Issue:**
- Adding New Code

**Language Used:**
- C++

**Comment by tauseefmohammed2** [comment]
I would be happy to do BST Implementation in C++ and contribute it to the repository as part for Hactoberfest.
If you like the idea please assign it to me.

**Comment by amritansh22** [comment]
Yes sure.

**Comment by Pratap2018** [comment]
assignme

**Comment by amritansh22** [comment]
@Pratap2018 This issue is already assigned. You may look for other issues or open your own here.
