### ISSUE TITLE
Binomial coefficients 

### ISSUE THREAD

**Issue by yash30201** [amritansh22/Data-Structures-and-Algorithms-in-cpp#108]
### Description 
C(n,r) describes the number of ways to choose r elements from n distinct elements. These are also known as binomial coefficients as they are coefficients of binomial series expansion.

### Deliverables
-  Code
-  Proper Comments for better understanding

### Language 
**C++**

@amritansh22  can you please assign this to me?

**Comment by amritansh22** [comment]
@yash30201 Done
