### ISSUE TITLE
Prime Factorisation of a positive number

### ISSUE THREAD

**Issue by yash30201** [amritansh22/Data-Structures-and-Algorithms-in-cpp#109]
### Description
Every natural number can be represented as a product of its prime factors and this form of representation is called prime factorisation form. So the problem is to prime factorise a natural number into its prime factors.

### Deliverables
- Code
- Comments for better understanding and explanation

### Language
**C++**

@amritansh22 Can you please assign this to me?

**Comment by amritansh22** [comment]
@yash30201 Done

**Comment by kratikaatgithub** [comment]
Hi @amritansh22 can I be assigned this issue as part of hacktoberfest?

**Comment by amritansh22** [comment]
@yash30201 I have assigned you already
