### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#11]
Add a file code file written in C++ of quick sort

**Comment by mahimagoyalx** [comment]
@amritansh22 I would like to work on this issue as a part of Hacktoberfest. Please assign it to me.

**Comment by amritansh22** [comment]
Assigning it to you. Just read the contribution guide and open a PR once done

**Comment by kratikaatgithub** [comment]
Hi can you assign this issue to me for Hacktoberfest 2020. 
Thanks

**Comment by mahimagoyalx** [comment]
@amritansh22 please assign one issue to only one person.
