### ISSUE TITLE
Extended Euclidean Algorithm

### ISSUE THREAD

**Issue by ArvindR07** [amritansh22/Data-Structures-and-Algorithms-in-cpp#110]
**Problem Statement:**
Given two integers a and b, represent their GCD (Greatest Common Divisor) in terms of a and b by finding suitable co-efficients.
(Eg.) a = 2 and b = 5
x = -2 and y = 1 because (-2) * 2 + (1) * 5 = 1 
where 1 is the GCD and x and y are co-efficients of a and b respectively.

**Comment by ArvindR07** [comment]
I am ready to contribute this problem. @amritansh22 
_Thank you._

**Comment by amritansh22** [comment]
@ArvindR07 assigned this issue to you.
