### ISSUE TITLE
Nth fibonacci using Recursion

### ISSUE THREAD

**Issue by reethikprasad** [amritansh22/Data-Structures-and-Algorithms-in-cpp#112]
Description
To find the nth fibonacci term using recursion

Deliverables
Code
Proper Comments for better understanding
Language
C++

@amritansh22 can you please assign this to me?

**Comment by Pratap2018** [comment]
i want to work on this

**Comment by amritansh22** [comment]
@reethikprasad Sure

**Comment by amritansh22** [comment]
@Pratap2018 This issue is already assigned. You may look for other issues or open your own here.

**Comment by Rune-Coder** [comment]
I see this issue is still open, I want to work on this issue. Please will you assign this to me?

**Comment by amritansh22** [comment]
@Rune-Coder This issue is already assigned. You may open up a new issue of you own choice here

**Comment by sanyasinghh25** [comment]
Can I contribute to this?

**Comment by amritansh22** [comment]
@sanyasinghh25 Yes sure
