### ISSUE TITLE
Disjoint Set Union (Data Structure)

### ISSUE THREAD

**Issue by yash30201** [amritansh22/Data-Structures-and-Algorithms-in-cpp#113]
### Description
DSU is a data structure with the following capabilities
- Combine any two different sets of elements.
- Tell in which set a specific element is present.

### Deliverables
- Code 
- Proper comments for better understanding of algorithms

### Language
**C++**

@amritansh22  Can you please assign this to me?

**Comment by amritansh22** [comment]
@yash30201 Done

**Comment by Aman2632** [comment]
@amritansh22 can I work on this issue

**Comment by amritansh22** [comment]
@Aman2632 Yes sure. Have assigned it to you.
