### ISSUE TITLE
Minimum Spanning Tree - Kruskal Algorithm

### ISSUE THREAD

**Issue by yash30201** [amritansh22/Data-Structures-and-Algorithms-in-cpp#114]
### Description
Minimum Spanning tree in a connected weighted graph is the tree whose sum of the weights is minimum possible. One of the algorithms which finds the MST is Kruskal.

### Deliverables
- Code - using STL library and DSU(Disjoint Set Union) data structure for checking cycles.
- Proper comments for better understanding of algorithms

### Language
**C++**

@amritansh22  Can you please assign this to me?

**Comment by amritansh22** [comment]
Already assigned

**Comment by yash30201** [comment]
Sorry my bad, I wasn't able to find the issue.
Thanks!

**Comment by amritansh22** [comment]
@yash30201 No problem
