### ISSUE TITLE
Minimum Spanning Tree - Prims Algorithm

### ISSUE THREAD

**Issue by yash30201** [amritansh22/Data-Structures-and-Algorithms-in-cpp#115]
### Description
Minimum Spanning tree in a connected weighted graph is the tree whose sum of the weights is minimum possible. One of the algorithms which finds the MST is Prims algorithm.

### Deliverables
- Code - using STL library
- Proper comments for better understanding of algorithms

### Language
**C++**

@amritansh22  Can you please assign this to me?

**Comment by amritansh22** [comment]
@yash30201 Done
