### ISSUE TITLE
Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by Ankitlenka26** [amritansh22/Data-Structures-and-Algorithms-in-cpp#116]
You are given an integer array nums sorted in ascending order, and an integer target.

Suppose that nums is rotated at some pivot unknown to you beforehand (i.e., [0,1,2,4,5,6,7] might become [4,5,6,7,0,1,2]).

If target is found in the array return its index, otherwise, return -1.

**Comment by Ankitlenka26** [comment]
I want to work on this

**Comment by amritansh22** [comment]
Yes ure @Ankitlenka26 Assigned it to you
