### ISSUE TITLE
Sudoku Solver Using Backtracking 

### ISSUE THREAD

**Issue by Ankitlenka26** [amritansh22/Data-Structures-and-Algorithms-in-cpp#117]
It's an Interesting problem and it will help solidify the understanding of backtracking. 
Can @amritansh22 you assign this to me and so I pull this code with comments in for hacktober fest.

**Comment by amritansh22** [comment]
Yes sure @Ankitlenka26

**Comment by Aditi-1400** [comment]
Hey, I would like to work on this issue!

**Comment by amritansh22** [comment]
Hey @Aditi-1400 Since this issue is already assigned you may look for other open issues or create your own here
