### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#12]
Add a file code file written in C++ of heap sort

**Comment by kratikaatgithub** [comment]
Hi I would like to work on this issue as part of Octoberfest. Plz assign this to me.
Thanks.

**Comment by khushi2912** [comment]
can you assign this to me please? @amritansh22

**Comment by amritansh22** [comment]
@kratikaatgithub @khushi2912 Anyone of you can do it. Just read the contribution guide and open a PR once done

**Comment by KalyanKumar-4** [comment]
how can we add local file to git repo?

**Comment by Priyanshu2802** [comment]
@amritansh22 Please let me contribute during event.

**Comment by amritansh22** [comment]
@Priyanshu2802 You can contribute anytime you feel. You can also open your own issues.

**Comment by amritansh22** [comment]
@KalyanKumar-4 I suppose you are using Github Web. After forking this repository, there is an option on top to add file
![image](https://user-images.githubusercontent.com/29978031/94355915-19104580-00a6-11eb-9807-a721d0b0d85d.png)
Click on it you can see the option to upload file.

**Comment by amritansh22** [comment]
@khushi2912 I have assigned this issue to you. Open a PR once done

**Comment by khushi2912** [comment]
Yes sure! @amritansh22
