### ISSUE TITLE
K coin Matrix Dp Problem 

### ISSUE THREAD

**Issue by Ankitlenka26** [amritansh22/Data-Structures-and-Algorithms-in-cpp#122]
It is one of the Multidimensional (3d) dynamic programming Problem with some elegant solution 
The problem is : 
Given a N x N matrix where every cell has some number of coins. Count number of ways to reach bottom right cell of matrix from top left cell with exactly K coins. We can move to (i+1, j) or (i, j+1) from a cell (i, j).
Input:
2
16
3
1 2 3 4 6 5 9 8 7
12
3
1 2 3 4 6 5 3 2 1

Output:
0
2

@amritansh22  can you assign this to me so I can work on it in Oct?

**Comment by Tripathi-Alok** [comment]
can you assign me this problem

**Comment by amritansh22** [comment]
@Tripathi-Alok This issue is already assigned you may look for other issues or open your own here
