### ISSUE TITLE
String: KMP Algorithm for Pattern Searching

### ISSUE THREAD

**Issue by Valkyrie006** [amritansh22/Data-Structures-and-Algorithms-in-cpp#124]
### Description
Given a pattern string and a text string, we have to find all the occurrences of pattern string in a text string.

### Deliverables

- Code

- Comments for better understanding and explanation

### Language
C++

@amritansh22 Can you please assign this to me?

**Comment by amritansh22** [comment]
@Valkyrie006 Please stop spamming this repository and verify before opening issue, if it already exits. Close all such issues and any further attempt like this by you will cause you to be removed from this repository
