### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#13]
Add a file code file written in C++ of merge sort

**Comment by mahimagoyalx** [comment]
@amritansh22 I would like to work on this issue as a part of Hacktoberfest. Please assign it to me.

**Comment by amritansh22** [comment]
@mahimagoyalx  I have assigned this issue to you. Read the contributing guidelines and open a PR once done.

**Comment by mahimagoyalx** [comment]
@amritansh22 Yes, sure, I will make the PR on 1st oct, also can I create more issues myself?

**Comment by kratikaatgithub** [comment]
Hi @amritansh22, can I also get assigned this task?

**Comment by amritansh22** [comment]
@mahimagoyalx Yes you are free to do so

**Comment by amritansh22** [comment]
@kratikaatgithub Done

**Comment by kratikaatgithub** [comment]
Thanks
