### ISSUE TITLE
Rat in a Maze 

### ISSUE THREAD

**Issue by Aditi-1400** [amritansh22/Data-Structures-and-Algorithms-in-cpp#134]
Implementation of Rat In a Maze problem using backtracking in CPP.

**Comment by Aditi-1400** [comment]
Hey, can I work on this issue?

**Comment by amritansh22** [comment]
Yes sure @Aditi-1400

**Comment by amritansh22** [comment]
Assigned this issue to you

**Comment by Aditi-1400** [comment]
Thank you ! :)
