### ISSUE TITLE
Shellsort.cpp

### ISSUE THREAD

**Issue by aniketsingh98571** [amritansh22/Data-Structures-and-Algorithms-in-cpp#138]
Shell sort is a highly efficient sorting algorithm and is based on insertion sort algorithm.
This algorithm avoids large shifts as in case of insertion sort, if the smaller value is to the far right 
and has to be moved to the far left.This algorithm uses insertion sort on a widely spread elements, first to sort 
them and then sorts the less widely spaced elements. This spacing is termed as interval.

@amritansh22  I would like to work on this issue for Hacktoberfest2020

**Comment by aniketsingh98571** [comment]
@amritansh22 I would like to work on this issue for Hacktoberfest2020. Please assign it to me.

**Comment by PriyanshuSaini** [comment]
@amritansh22  I want to work on this issue, and i will provide better explaination along with code.Please assign this to me.

**Comment by amritansh22** [comment]
@PriyanshuSaini This issue is already assigned. You may look for other issues or open your own here.
