### ISSUE TITLE
MAXIMUM SUBARRAY

### ISSUE THREAD

**Issue by utchak160** [amritansh22/Data-Structures-and-Algorithms-in-cpp#139]
**Description**
Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.

Example 1:

Input: nums = [-2,1,-3,4,-1,2,1,-5,4]
Output: 6
Explanation: [4,-1,2,1] has the largest sum = 6.
Example 2:

Input: nums = [1]
Output: 1

@amritansh22  can I work on this program for Hacktober fest 2020?

**Comment by amritansh22** [comment]
@utchak160 This is already implemented. You may try something other.
