### ISSUE TITLE
Binary matrix

### ISSUE THREAD

**Issue by chaturvediabhay24** [amritansh22/Data-Structures-and-Algorithms-in-cpp#140]
N numbers were converted into their respective Binary form of M length and arranged in an NxM matrix.

Your task is to find the index of row (1 based indexing) which contains the binary number with maximum value. If multiple rows have maximum value then print the row with minimum index.

Input:

The first line contains two space separated integers N and M, denoting number of rows and number of columns in matrix respectively.

Each of the next N lines contains a number in binary form.

Output:

Print the index of row in a single line.

HI @amritansh22 i would like to work on this issue. please assign this to me.

**Comment by amritansh22** [comment]
Yes sure @chaturvediabhay24
