### ISSUE TITLE
Peak Element in an Array

### ISSUE THREAD

**Issue by ArvindR07** [amritansh22/Data-Structures-and-Algorithms-in-cpp#143]
**Problem Statement:**

Given an array of n elements, find the position of the element which is greater than or equal to both of its neighboring elements.

**Notes:** 

- First and last elements have only one neighbor. 
- It is guaranteed that at-least one peak exists. 
- Do not use linear scan. 
- Your program should run in logarithmic complexity.

**Comment by ArvindR07** [comment]
I  would be happy to contribute to this issue. @amritansh22 
_Thank you! :)_

**Comment by amritansh22** [comment]
Yes sure @ArvindR07 assigned it to you
