### ISSUE TITLE
Count ways to reach the n'th stair - dynamic programming

### ISSUE THREAD

**Issue by PriyanshuSaini** [amritansh22/Data-Structures-and-Algorithms-in-cpp#146]
There are N stairs, a person standing at the bottom wants to reach the top. The person can climb either 1 stair or 2 stairs at a time. Count the number of ways, the person can reach the top (order does matter).

Input:
The first line contains an integer 'T' denoting the total number of test cases. In each test cases, an integer N will be given.

Output:
For each testcase, in a new line, print number of possible ways to reach Nth stair. Answer your output % 10^9+7.

Expected Time Complexity : O(N)
Expected Auxiliary Space: O(1)

Constraints:
1 <= T <= 105
1 <= N <= 105

Example:
Input:
3
4
10
24
Output:
5
89
75025
Explanation:
Testcase 1: You can reach 3rd stair in 5 ways.

@amritansh22  can i add this? Please assign this to me

**Comment by amritansh22** [comment]
Yes sure @PriyanshuSaini I have assigned this issue to you.
