### ISSUE TITLE
Minimum Swaps to Sort

### ISSUE THREAD

**Issue by PriyanshuSaini** [amritansh22/Data-Structures-and-Algorithms-in-cpp#147]
Given an array of integers. Find the minimum number of swaps required to sort the array in non-decreasing order.

Input:
The first line of input contains an integer T denoting the no of test cases. Then T test cases follow. Each test case contains an integer N denoting the no of element of the array A[ ]. In the next line are N space separated values of the array A[ ] .

Output:
For each test case in a new line output will be an integer denoting  minimum umber of swaps that are  required to sort the array.

Constraints:
1 <= T <= 100
1 <= N <= 105
1 <= A[] <= 106 

Expected Time Complexity: O(NlogN).
Expected Auxiliary Space: O(N).

Example(To be used only for expected output):
Input:
2
4
4 3 2 1
5
1 5 4 3 2

Output:
2
2

Explanation:
Test Case 1: We need two swaps, swap 1 with 4 and 3 with 2 to make it sorted.
Test Case 2: We need two swaps, swap 2 with 5 and 3 with 4 to make it sorted. 

@amritansh22  please assign this to me, i want to work on this.

**Comment by raj292** [comment]
Hey, I would like to contribute to this problem

**Comment by PriyanshuSaini** [comment]
@amritansh22 i asked in the comment already sir
.

**Comment by amritansh22** [comment]
Yes sure. I have assigned the issue to you
