### ISSUE TITLE
Kadane's Algorithm 

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#15]
Add a code file in C++ of Kadane's Algorithm

**Comment by yadavKaustubh** [comment]
@amritansh22  can you assign me this issue

**Comment by khushi2912** [comment]
@amritansh22 Can you assign this issue to me?

**Comment by iaish-max** [comment]
I am beginner in open source github,can you assign me this issue.

**Comment by ayush523** [comment]
Hi @amritansh22 .I would like to work on this issue.Can you help me how to get started?

**Comment by amritansh22** [comment]
@ayush523 Yes please go ahead.
