### ISSUE TITLE
Tree: Inorder Traversal

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#16]
Add a code file in C++ of Inorder Traversal

**Comment by PrakharQ** [comment]
Recursive or Iterative ?

**Comment by amritansh22** [comment]
It's completely your choice.

**Comment by amritansh22** [comment]
I am assigning this issue to you.

**Comment by dolonmandal** [comment]
can I work on this as a part of hacktoberfest?

**Comment by muskan-goel09** [comment]
I would really like to contribute

**Comment by amritansh22** [comment]
@muskan-goel09 There are plenty of issues to work upon, choose the one that you are most comfortable working on or open issues of your own. Make sure to follow all the points of the contribution guidelines and make a PR once done.

**Comment by amritansh22** [comment]
@muskan-goel09 Do you want this issue to be assigned to you?

**Comment by arnabsen1729** [comment]
@amritansh22 I would love to contribute this repo. This repo has already helped me a lot, I would to love to contribute to it more.

**Comment by amritansh22** [comment]
@arnabsen1729 It's nice to hear that this repository helped you. You can open PR on topics that have not been added till now.

**Comment by arnabsen1729** [comment]
@amritansh22 yes, I just did. https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/issues/100 Its issue 100 :). I would keep contributing more.

**Comment by piyush9311** [comment]
May I work on this issue pls
