### ISSUE TITLE
clockwise rotation of linkedlist

### ISSUE THREAD

**Issue by Ajit-53** [amritansh22/Data-Structures-and-Algorithms-in-cpp#187]
well optimize code in c++ with documentation...

**Comment by Ajit-53** [comment]
@amritansh22 can you please assign this issue to me..

**Comment by Ajit-53** [comment]
i don't think its optimize one and you directly copy this code from https://geektech1717.blogspot.com/2020/06/clockwise-rotation-of-linked-list.html @Praddyumn16

**Comment by amritansh22** [comment]
Yes sure. I have assigned the issue to you

**Comment by Praddyumn16** [comment]
So, are we not supposed to push the code from somewhere else. 
Because i thought at the end am contributing in the repository , so the origin of the code won't matter. Please correct me if am wrong @Ajit-53
