### ISSUE TITLE
Tree: Level Order Traversal

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#19]
Add a code file in C++ of Level Order Traversal

**Comment by milanj-1** [comment]
could you assign this to me?

**Comment by khushi2912** [comment]
i can work on this, can you assign this to me? @amritansh22

**Comment by amritansh22** [comment]
@milanj-1 @khushi2912 Anyone of can do it. Just read the contribution guide and open a PR once done

**Comment by rasacharjee** [comment]
can I work and open a pr

**Comment by amritansh22** [comment]
@rasacharjee Yes sure please go ahead

**Comment by rasacharjee** [comment]
Thanks for helping me contribute to the issue. I have made a pr .I would be grateful if that's merged.
