### ISSUE TITLE
first_missing_positive _integer

### ISSUE THREAD

**Issue by ishi0301** [amritansh22/Data-Structures-and-Algorithms-in-cpp#192]

**Comment by m-e-r-l-i-n** [comment]
can i do this?

**Comment by Ajit-53** [comment]
can you please assign this issue to me.

**Comment by ishi0301** [comment]
@Ajit-53 i have created this issue for myself. Kindly make your own issue and make  your PR.

**Comment by Ajit-53** [comment]
please mention it in the comment section.when you create issues.
