### ISSUE TITLE
finding nCr

### ISSUE THREAD

**Issue by m-e-r-l-i-n** [amritansh22/Data-Structures-and-Algorithms-in-cpp#194]
find nCr value modulo M
1<=n<=10^5
1<=r<=10^5
M is a prime

**Comment by m-e-r-l-i-n** [comment]
can i work on this?

**Comment by MisterSingh** [comment]
Added nCr in [this](https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/pull/197)

**Comment by m-e-r-l-i-n** [comment]
> Added nCr in [this](https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/pull/197)

[this](https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/pull/197) will fail for large values of n and r
check [my pr](https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/pull/198) for the edits i am suggesting

**Comment by MisterSingh** [comment]
@m-e-r-l-i-n  Can you give me an example for which it will fail?

**Comment by m-e-r-l-i-n** [comment]
n=2*10^4 r=10^4 M=10^9+7
