### ISSUE TITLE
Matrix Diagonal Sum

### ISSUE THREAD

**Issue by nischalsoni** [amritansh22/Data-Structures-and-Algorithms-in-cpp#206]
Given a square matrix `mat`, return the sum of the matrix diagonals.

Only include the sum of all the elements on the primary diagonal and all the elements on the secondary diagonal that are not part of the primary diagonal.

**Comment by YUVRAJMOTWANI99** [comment]
@amritansh22 pls assign this to me.

**Comment by AnuragGupta806** [comment]
Can i do it?

**Comment by nischalsoni** [comment]
@AnuragGupta806 actually, this issue has been closed in the PR #207 . You can always open a new issue yourself.
