### ISSUE TITLE
Subset Problem

### ISSUE THREAD

**Issue by Harshit11072000** [amritansh22/Data-Structures-and-Algorithms-in-cpp#219]

**Comment by Harshit11072000** [comment]
Please Assign

**Comment by deytulsi18** [comment]
May I do this please?

**Comment by deytulsi18** [comment]
can I contribute?

**Comment by deytulsi18** [comment]
I have sent PR for the solution please merge it
[#224 ](https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/pull/224)
