### ISSUE TITLE
Multiplication w/o using multiplication operator.

### ISSUE THREAD

**Issue by Rajdeep-G** [amritansh22/Data-Structures-and-Algorithms-in-cpp#230]
I will write a code with full documentation about how to find the product of two numbers without using the multiplication (*) operation.

**Comment by amritansh22** [comment]
Yes sure. I have assigned the issue to you

**Comment by AviSharma1305** [comment]
I'd like to write the code for multiplying 2 numbers without using ( * ) operator.

**Comment by distroinfinity** [comment]
I see the issue is still open, I can write the code. Please let me know in which directory to place the cpp file @amritansh22

**Comment by amritansh22** [comment]
Yes sure you may take it @distroinfinity

**Comment by Deepak2417** [comment]
I am willing to work on this using C++. Kindly assign this to me also.

**Comment by amritansh22** [comment]
@Deepak2417 Yes sure. Open a PR once done

**Comment by prabhat34** [comment]
i want to contribute , could you pls assign it to me?

**Comment by prabhat34** [comment]
I am willing to do this issue , could you pls assign it to me?
