### ISSUE TITLE
Move all sorting algorithms to one new folder

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#235]

**Comment by d2Anubis** [comment]
I want to do this.

**Comment by harshgoel05** [comment]
Can I work on this? Seems good to do.

**Comment by d2Anubis** [comment]
I will also try to add if any are missing.

**Comment by deytulsi18** [comment]
I have moved all sorting algos into one folder,
please merge my PR
[Added all sort algo in one folder](https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/pull/239)
