### ISSUE TITLE
Multiply two sparse matrix #281

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#282]

**Comment by Pacifier25** [comment]
can i work in this issue?

**Comment by amritansh22** [comment]
Yes sure @Pacifier25  I have assigned it to you

**Comment by Pacifier25** [comment]
Actually I have some doubt as this is my first issue.
do i have to create a program that multiply two sparse and merge in this project am i correct

**Comment by amritansh22** [comment]
@Pacifier25 Yes exactly.

**Comment by abhi2694** [comment]
@amritansh22 I would like to take this up.
