### ISSUE TITLE
Find nth Ugly number 

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#285]

**Comment by kartikeytyagi15** [comment]
Can i try this out in java?

**Comment by amritansh22** [comment]
Hey @kartikeytyagi15 this repository is explicitly for C++ only. If you are not comfortable in it, you can move all the sorting algorithms in to their folder and open a PR

**Comment by kartikeytyagi15** [comment]
Ill do it in C++

**Comment by amritansh22** [comment]
ok @kartikeytyagi15 I have assigned this issue to you

**Comment by HarshithB** [comment]
@amritansh22 how many sorting algorithms can I try

**Comment by amritansh22** [comment]
@HarshithB You have to just move the sorting files to the SortingAlgorithms folder. There are about 7 to 10 sorting algorithms. If there are any duplicates then remove one of them

**Comment by HarshithB** [comment]
@amritansh22 Done I have just moved a new sorting file to SortingAlgorithms Folder.

**Comment by kartikeytyagi15** [comment]
Done , do let me know if there is any issue.

**Comment by amritansh22** [comment]
@kartikeytyagi15 I have assigned this issue, open a PR once done

**Comment by HarshithB** [comment]
@amritansh22 I have done my part

**Comment by amritansh22** [comment]
@kartikeytyagi15 The volume of incoming PR's is huge, so it is taking a bit of time. Your PR is now merged
