### ISSUE TITLE
Convert matrix to sparse matrix

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#286]

**Comment by Prash2002** [comment]
hey @amritansh22 , 
I would like to contribute,
can you assign it to me?

**Comment by amritansh22** [comment]
Yes sure @Prash2002  I have assigned it to you

**Comment by Prash2002** [comment]
> Yes sure @Prash2002 I have assigned it to you

Thanks

**Comment by Prash2002** [comment]
hey @amritansh22 ,
I've completed it, please check : https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/pull/303

**Comment by abhishek7553** [comment]
can you assign me this or other problem

**Comment by Aj12345616** [comment]
hey @amritansh22 can you assign me in this task i would like to make pull request towards hactoberfest....
