### ISSUE TITLE
Level order traversal of a tree 

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#287]

**Comment by AparnaJuhi** [comment]
I want to work on this issue. Please assign it to me!

**Comment by amritansh22** [comment]
Yes sure @AparnaJuhi  I have assigned it to you

**Comment by AparnaJuhi** [comment]
@amritansh22  I have completed level order traversal. Please review my PR and merge my code.
