### ISSUE TITLE
Graphs: Depth First Search

### ISSUE THREAD

**Issue by KartikeySharma** [amritansh22/Data-Structures-and-Algorithms-in-cpp#31]
Hi
I would like to contribute to this repository. I would like to add some algorithms related to graphs and strings.Can you pls assign DFS to me for Hacktoberfest?
Thanks

**Comment by KartikeySharma** [comment]
Also, pls add the labels of Hacktoberfest if possible.

**Comment by shaonakundu** [comment]
Hey @amritansh22 I would like to add some problems like permutations using DFS and few more related to DFS, so can you assign me this issue?

**Comment by KartikeySharma** [comment]
@shaonakundu  You can open a different issue and work on that I guess.

**Comment by amritansh22** [comment]
@shaonakundu Yes you can. Please read the contribution guidelines and make sure to follow all the steps and open a Pull Request once done.

**Comment by shaonakundu** [comment]
> @shaonakundu Yes you can. Please read the contribution guidelines and make sure to follow all the steps and open a Pull Request once done.

Can't I use python?

**Comment by KartikeySharma** [comment]
@shaonakundu The repository says cpp :)

**Comment by amritansh22** [comment]
@shaonakundu This repository is exclusively for DS in C++. I went through your profile and saw you more into development. 
I am assigning some easy tasks to you in this repository whose tech stack matches your. https://github.com/amritansh22/Object-Detection-and-Extraction
