### ISSUE TITLE
Search in a Bitonic Array

### ISSUE THREAD

**Issue by noob-26** [amritansh22/Data-Structures-and-Algorithms-in-cpp#316]
Given an array arr[] that is increasing first and then decreasing and a number key, find the index of the number in the array if present, else return -1.

Input 1 :  arr[] = {-3, 9, 8, 20, 17, 5, 1};
            key = 20
Output 1  : Found at index 3

Input 2 :  arr[] = {5, 6, 7, 8, 9, 10, 1, 2, 3};
               key = 30
Output 2  : Not Found 

Can I Work on this issue @amritansh22 ?

**Comment by amritansh22** [comment]
Yes sure. I have assigned the issue to you.

**Comment by noob-26** [comment]
Thanks a lot.
