### ISSUE TITLE
Climbing Stairs

### ISSUE THREAD

**Issue by utchak160** [amritansh22/Data-Structures-and-Algorithms-in-cpp#330]
**Description**
You are climbing a staircase. It takes n steps to reach to the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

Example 1:

Input: 2
Output: 2
Explanation: There are two ways to climb to the top.
1. 1 step + 1 step
2. 2 steps

Example 2:

Input: 3
Output: 3
Explanation: There are three ways to climb to the top.
1. 1 step + 1 step + 1 step
2. 1 step + 2 steps
3. 2 steps + 1 step

@amritansh22  can I solve this program? Please assign it to me.

**Comment by iFrogHop2Worlds** [comment]
Can I be assigned this problem please?

**Comment by amritansh22** [comment]
Already implemented.
