### ISSUE TITLE
Binary Tree Level Order Traversal

### ISSUE THREAD

**Issue by shreyavanga** [amritansh22/Data-Structures-and-Algorithms-in-cpp#333]
Given a binary tree, return the level order traversal of its nodes' values. (ie, from left to right, level by level).

For example:
Given binary tree [3,9,20,null,null,15,7]
return its level order traversal as:
[
  [3],
  [9,20],
  [15,7]
]

Can I work on adding this problem as a part of Dp Alogrithms @amritansh22

**Comment by iFrogHop2Worlds** [comment]
can I get assigned this?

**Comment by amritansh22** [comment]
Already implemented @shreyavanga
