### ISSUE TITLE
Next Similar Number

### ISSUE THREAD

**Issue by jyotiGambhir** [amritansh22/Data-Structures-and-Algorithms-in-cpp#337]
Given a number A in a form of string.You have to find the smallest number that has same set of digits as A and is greater than A.
If A is the greatest possible number with its set of digits, then return -1.
Problem Constraints
1 <= A <= 10100000
A doesn't contain leading zeroes.
Input Format
First and only argument is an numeric string denoting the number A.
Output Format
Return a string denoting the smallest number greater than A with same set of digits , if A is the largest possible then return -1.
Example Input
Input 1:
A = "218765"
Input 2:
A = "4321"
Example Output
Output 1:
"251678"
Output 2:
"-1"

Can I work on this under Maths and Array section?

**Comment by amritansh22** [comment]
Yes sure. I have assigned it to you
