### ISSUE TITLE
Minimum in sub-array using Segment Tree in cpp

### ISSUE THREAD

**Issue by Nishant763** [amritansh22/Data-Structures-and-Algorithms-in-cpp#338]
<b>Minimum In SubArray</b>

<b>Range Minimum Query</b>
Given an array A of size N, there are two types of queries on this array.

1) q l r: In this query you need to print the minimum in the sub-array A[l:r].
2) u x y: In this query you need to update A[x]=y.

<b>Input:</b>
First line of the test case contains two integers, N and Q, size of array A and number of queries.
Second line contains N space separated integers, elements of A.
Next Q lines contain one of the two queries.

<b>Output:</b>
For each type 1 query, print the minimum element in the sub-array A[l:r].

<b>Contraints:</b>
1≤N,Q,y≤10^5
1≤l,r,x≤N

<b>Sample Input :</b>
5 5
1 5 2 4 3
q 1 5
q 1 3
q 3 5
u 3 6
q 1 5

<b>Sample Output :</b>
1
1
2
1

**Comment by AnshMishra2001** [comment]
Can I work on this issue?

**Comment by Nishant763** [comment]
@AnshMishra2001 Sorry, I have already generated a PR request for this issue. You can create your own issues and work on them.
