### ISSUE TITLE
Graphs: Breadth First Search

### ISSUE THREAD

**Issue by KartikeySharma** [amritansh22/Data-Structures-and-Algorithms-in-cpp#34]
Hi
I would like to contribute to this repository. I would like to work on graphs and BFS . Can you pls assign BFS to me for Hacktoberfest?
Thanks

**Comment by amritansh22** [comment]
@KartikeySharma Yes please go ahead.

**Comment by KartikeySharma** [comment]
I have added the BFS algorithm too along with the DFS implementation. That's why I closed this issue :)
