### ISSUE TITLE
Patching Array

### ISSUE THREAD

**Issue by sdatrey** [amritansh22/Data-Structures-and-Algorithms-in-cpp#346]
Given a sorted positive integer array nums and an integer n, add/patch elements to the array such that any number in range [1, n] inclusive can be formed by the sum of some elements in the array. Return the minimum number of patches required.

Example: 
Input: nums = [1,5,10], n = 20
Output: 2
Explanation: The two patches can be [2, 4].

Can i contribute into this algorithm? @amritansh22

**Comment by amritansh22** [comment]
Yes sure.

**Comment by amritansh22** [comment]
Assigned you @sdatrey
