### ISSUE TITLE
Implement Kruskal’s Minimum Spanning Tree Algorithm

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#35]
Implement code file of Kruskal’s Minimum Spanning Tree Algorithm in C++

**Comment by ujjwal404** [comment]
Hi, I would like to work on this as a part of hacktober fest. Can you please assign it to me.

**Comment by amritansh22** [comment]
Yes please go ahead @ujjwal404

**Comment by amritansh22** [comment]
@ujjwal404 Are you still up on this issue?

**Comment by ujjwal404** [comment]
Yes, I've taken up this issue for hacktober fest. I'll make a pull request on 1 oct. If it's really important I can make a pr tomorrow too.

**Comment by rishavraj5** [comment]
Hi, I would like to work on this issue.

**Comment by amritansh22** [comment]
@rishavraj5 Already implemented
