### ISSUE TITLE
Implement Stack using array

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#36]
Implement Stack using array

**Comment by mayankkagrawal** [comment]
[StackUsingArray.zip](https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/files/5283662/StackUsingArray.zip)

**Comment by jakansha2001** [comment]
Can I work on this issue??

**Comment by amritansh22** [comment]
@mayankkagrawal This is not the way how we push code. I suggest you to please learn about github and then try again.

**Comment by amritansh22** [comment]
@jakansha2001 Yes please go ahead and please make sure to follow all the points of the contribution guidelines. I am assigning this issue to you.

**Comment by jakansha2001** [comment]
yes sure thank you!

**Comment by jakansha2001** [comment]
i was working with this issue what happened?

**Comment by amritansh22** [comment]
extremely sorry @jakansha2001 I was closing another issue but by mistake I did this one

**Comment by amritansh22** [comment]
@jakansha2001 I have reopened the issue and assigned it to you

**Comment by jakansha2001** [comment]
okay thanks
