### ISSUE TITLE
Sliding Window Maximum

### ISSUE THREAD

**Issue by Himanshu16Singh** [amritansh22/Data-Structures-and-Algorithms-in-cpp#395]
The problem is  : 
    given an array and an integer k, find the maximum for each
    and every contiguous subarray of size k.
    Input:
    arr[] = {1, 2, 3, 1, 4, 5, 2, 3, 6}
    k = 3
    Output :
    3 3 4 5 5 5 6

**Comment by Himanshu16Singh** [comment]
Can I make a PR for this ?

**Comment by amritansh22** [comment]
Yes sure. Assigned it to you
