### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by abhi2694** [amritansh22/Data-Structures-and-Algorithms-in-cpp#403]
Having a folder structure helps to keep track of all the resources and algos in a proper manner. This issue addresses the folder structure problem, which aims at updating the readme such that it becomes easier for first-timers to contribute to this repository and maintain code structure in a proper manner.
I would like to take this up.

**Comment by amritansh22** [comment]
Assigned it to you @abhi2694

**Comment by megha070** [comment]
@amritansh22 I would like to take this up. For I am planning to add a first timers guide for users who are looking forward to their first contribution in this repo.

**Comment by amritansh22** [comment]
@megha070 This is already implemented. You may try something other.
