### ISSUE TITLE
Move all DP solutions to one foleder

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#414]

**Comment by raj2729** [comment]
Hi @amritansh22 , i had like to do this could you please assign me for the same ?

**Comment by amritansh22** [comment]
Yes sure @raj2729 I have assigned this issue to you.

**Comment by amritansh22** [comment]
@raj2729 Create a new folder named **Dynamic Programming** and move all the files in the main directory of  Dynamic Programming  to the newly created folder

**Comment by raj2729** [comment]
@amritansh22 Do you also require me to move the following folders : "Kth Largest" , "SearchingAlgorithms" and "SortingAlgorithms" to the new folder Dynammic Programming where I have added all .cpp files ?

**Comment by amritansh22** [comment]
No not them, just the files implementing some dp problem

**Comment by raj2729** [comment]
Okay @amritansh22  . I will work on it accordingly .
It would be really helpful if you add hacktoberfest-accepted / hacktober label . Thank you

**Comment by raj2729** [comment]
I have created the pull request . Please do check that out and do let me know if you require any changes .
