### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#42]
Implement Longest Common Subsequence in C++

**Comment by Narapureddy-Srikanth** [comment]
Hello, I would like to work on implementing Longest Common Subsequence in C++ as a part of hacktober fest. Can you please assign it to me.

**Comment by amritansh22** [comment]
Yes sure @Narapureddy-Srikanth Please read the contribution guidelines and make to sure to follow all the points. Open a PR once done

**Comment by Maitryee-Choudhary** [comment]
I would like to  work on this.Can you assign it to me?

**Comment by dolonmandal** [comment]
I would like to work on this as a part of hacktober fest 2020. Can you please assign it to me.

**Comment by amritansh22** [comment]
@Maitryee-Choudhary @dolonmandal This issue is currently open and not assigned to anyone anyone of you can do this and open a PR. I will the merge whose I receive first. You can also work on some of your own issues

**Comment by amritansh22** [comment]
@Narapureddy-Srikanth  Are you still up on this issue?
