### ISSUE TITLE
Insertion sort

### ISSUE THREAD

**Issue by Rune-Coder** [amritansh22/Data-Structures-and-Algorithms-in-cpp#424]
I will like to work in this

**Comment by amritansh22** [comment]
Sure Have assigned this issue

**Comment by Rune-Coder** [comment]
Okay @amritansh22 . I will work on it accordingly .
It would be really helpful if you add hacktoberfest-accepted / hacktober label . Thank you.

**Comment by amritansh22** [comment]
@Rune-Coder Done

**Comment by coolsks** [comment]
I would like to contribute on this .

**Comment by amritansh22** [comment]
@coolsks This issue is already taken. You may open some other issues of your own choice here.

**Comment by aryangupta02092002** [comment]
### Insertion Sort
`#include<stdio.h>
#include<math.h>
void insertionsort(int a[], int n)
{
    int i,j,tmp;
    for(i=1;i<n;i++)
    {
        tmp=a[i];
        j=i-1;
        while(j>=0&&a[j]>tmp)
        {
            a[j+1]=a[j];
            j--;
        }
        a[j+1]=tmp;
    }
}
void printArray(int a[], int n)
{
    int i;
    for (i = 0; i < n; i++)
        printf("%d ", a[i]);
    printf("\n");
}
int main()
{
    int a[30];
    int k,n;
    printf("Enter total no. of elements to be inserted:");
    scanf("%d",&n);
    printf("Enter elements:");
    for(k=0;k<n;k++)
    {
        scanf("%d",&a[k]);
    }
    insertionsort(a,n);
    printArray(a,n);
    return 0;
}
`

**Comment by amritansh22** [comment]
@aryangupta02092002 This isn't how Github works, you may first learn it or read the contribution guidelines here
