### ISSUE TITLE
Max product Subarray

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#43]
Implement Max product Subarray in C++

**Comment by Narapureddy-Srikanth** [comment]
Hello, I would like to work on implementing Max product Subarray in C++ as a part of hacktober fest. Can you please assign it to me.

**Comment by amritansh22** [comment]
Yes sure @Narapureddy-Srikanth Please read the contribution guidelines and make to sure to follow all the points. Open a PR once done

**Comment by Praddyumn16** [comment]
@amritansh22 I would like to contribute in this repository because i have good hold on DSA in cpp but every issue has already been assigned to someone. So could you please assign some issue to me as well if in case someone has been assigned more than one issue.

**Comment by amritansh22** [comment]
@Praddyumn16 you can yourself open issues also. I am also adding new issues periodically.

**Comment by Praddyumn16** [comment]
Okay, that means i can write other algorithms on my own too and push them with a pull request !!

**Comment by amritansh22** [comment]
@Praddyumn16 Exactly Just follow all the steps from here: https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp#how-to-contribute

**Comment by amritansh22** [comment]
@Narapureddy-Srikanth Are you still up on this issue?
