### ISSUE TITLE
Shortest Subarray with Sum at Least K

### ISSUE THREAD

**Issue by Sinha199** [amritansh22/Data-Structures-and-Algorithms-in-cpp#430]
I will like to work on this problem. Please assign this to me, also add hacktoberfest 2020 label.

**Comment by amritansh22** [comment]
Yes sure @Sinha199 Have assigned it  to you.

**Comment by YashJain2** [comment]
I would like to contribute on this one under hacktoberfest.
Please assign it to me if possible.
@amritansh22

**Comment by amritansh22** [comment]
@YashJain2 This issue is already taken you may open some other issue of your own choice here
