### ISSUE TITLE
Check balanced balance parentheses 

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#44]
Implement a code file in C++ to check balanced balance parentheses

**Comment by aswarth123** [comment]
I would like to solve it can you assign it to me?

**Comment by amritansh22** [comment]
@aswarth123  Yes please go ahead.

**Comment by poojitha2002** [comment]
Can I also contribute my code and explanation?

**Comment by amritansh22** [comment]
@poojitha2002 Since this issue is already assigned, you can create some other issue and work on it.
