### ISSUE TITLE
Search an element in Linked List

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#45]
Implement a code file in C++ to search an element in Linked List

**Comment by aswarth123** [comment]
I would like to solve it can you assign it to me?

**Comment by hbach24** [comment]
Can I try this issue?

**Comment by hbach24** [comment]
May I take this issue?

**Comment by amritansh22** [comment]
@aswarth123 I have assigned you another issue. Let this be taken by @hbach24

**Comment by aswarth123** [comment]
ok no problem.

**Comment by hbach24** [comment]
Thank you! I have a question regarding this issue. Would you want me to manually create my own linked list? And also would you want it to return a boolean value (true/false) if an element is found?

**Comment by amritansh22** [comment]
@hbach24 Yes you have to create your own LL and return a Boolean value

**Comment by Soham182001** [comment]
Can I try this ? I have a implemented code of searching a number in linked list written in C I will just write it in C++.

**Comment by amritansh22** [comment]
Yes sure @Soham182001

**Comment by Soham182001** [comment]
please open this!

**Comment by amritansh22** [comment]
@Soham182001 Despite being closed, you can still work on this
