### ISSUE TITLE
Implement a code file in C++ for Tower of Hanoi

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#46]
Implement a code file in C++ for Tower of Hanoi problem

**Comment by moddamatt** [comment]
Hello I'll take a crack at the Tower of Hanoi. You can assign it to me.

**Comment by amritansh22** [comment]
Yes please go ahead @moddamatt Open a PR once done. I have assigned this issue

**Comment by ayush523** [comment]
Hi @amritansh22 ,I have worked on this issue.
