### ISSUE TITLE
Any data structures and algorithms left for me to complete?

### ISSUE THREAD

**Issue by jdouglass** [amritansh22/Data-Structures-and-Algorithms-in-cpp#472]
Hi, I'm looking to make my first ever contribution to a project on github and to practice my C++ skills. Are there any more data structures and algorithms left for me to complete on this project?

**Comment by amritansh22** [comment]
@jdouglass Yes there are a lot of data structures yet to be implemented. You can explore the repository and open a PR once done.

**Comment by himanshu007-creator** [comment]
i have a problem that should be included here . IF interested please allow me to contribute

**Comment by amritansh22** [comment]
@himanshu007-creator Yes you may.

**Comment by himanshu007-creator** [comment]
So i just add the file right?

**Comment by amritansh22** [comment]
@himanshu007-creator yes add it, then it will be reviewed

**Comment by TermKnive** [comment]
i have submitted a pull request, please check it, thx!

**Comment by amritansh22** [comment]
@TermKnive Done.

**Comment by TermKnive** [comment]
Aight thx

**Comment by anishsingh935** [comment]
HI I have two more algorithm that should be included here .IF interested please allow me to contribute

**Comment by anishsingh935** [comment]
Moore's voting algorithm [code to find majority of element in less time complexity ]
jungling algorithm [to rotate the array according to given no ].

**Comment by TruePadawan** [comment]
@amritansh22 check my own pull request
