### ISSUE TITLE
Find Largest area of Histogram in CPP

### ISSUE THREAD

**Issue by micky2001** [amritansh22/Data-Structures-and-Algorithms-in-cpp#481]

**Comment by killerzula** [comment]
any details?

**Comment by killerzula** [comment]
@amritansh22 i wanted to work on this problem. Can i still solve this and send a PR?

**Comment by amritansh22** [comment]
@killerzula Yes sure. Go ahead. Open a PR once done and I will merge it.

**Comment by killerzula** [comment]
ok thanks
