### ISSUE TITLE
Add c++ code for Lowest common ancestor in a tree

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#498]

**Comment by rohan26062001** [comment]
Please Assign me, I can work on this

Thank you

**Comment by amritansh22** [comment]
@rohan26062001  Start working on it. Open a PR once done

**Comment by amritansh22** [comment]
@rohan26062001 Please take some other code of your choice. This is already taken.
