### ISSUE TITLE
Implement 0/1 Knapsack in c++

### ISSUE THREAD

**Issue by dolonmandal** [amritansh22/Data-Structures-and-Algorithms-in-cpp#53]

**Comment by dolonmandal** [comment]
I am a  beginner in hacktoberfest and this is my first issue. Now should I have to wait for this task to be assigned to me?

**Comment by amritansh22** [comment]
@dolonmandal I have assigned this issue to you. Make sure to follow all the points mentioned in the contributing guidelines and open open a PR once done.
