### ISSUE TITLE
Nth Fibonacci Number

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#55]
Write a code file in C++ to print the Nth Fibonacci Number

**Comment by Maitryee-Choudhary** [comment]
I would to work on this.Can you assign me?

**Comment by amritansh22** [comment]
@Maitryee-Choudhary You can work on this. Read the contribution guidelines and make sure to follow all points and open a PR once done.

**Comment by sakshi-choudhary** [comment]
Can I work on this?

**Comment by amritansh22** [comment]
@Maitryee-Choudhary are you on this or should I assign it to @sakshi-choudhary ?

**Comment by sakshi-choudhary** [comment]
@amritansh22 you have to assign me.

**Comment by amritansh22** [comment]
@sakshi-choudhary Let me first ask if @Maitryee-Choudhary is still working on it. In the meantime you can see other issues or open your own issues.

**Comment by Maitryee-Choudhary** [comment]
Yes I am working on it.

**Comment by amritansh22** [comment]
@Maitryee-Choudhary Great.
