### ISSUE TITLE
Reverse an array

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#56]
Write a code file in C++ to reverse a 1D array

**Comment by Manoj13-coder** [comment]
I would love to contribute

**Comment by gayatri517** [comment]
I would like to work on this issue please assign me

**Comment by amritansh22** [comment]
@gayatri517 Yes please go ahead. Make sure to follow all the points of the contribution guidelines and open a PR once done.

**Comment by gayatri517** [comment]
Thank you, i will put a PR on 1st October.
