### ISSUE TITLE
Left rotate an array k times

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#57]

**Comment by Ajit-53** [comment]
i would like to work on this.Can you please assign me?

**Comment by amritansh22** [comment]
@Ajit-53  You may start working on this and open a PR once done. Make sure to follow all the points of the contribution guidelines.

**Comment by Ajit-53** [comment]
i have one doubt regarding this  i know bruteforce and most optimize
algorithm too.. what i have to submit both are most optimize..thanks for
your response.

**Comment by amritansh22** [comment]
@Ajit-53 You should definitely summit the optimized one.

**Comment by amritansh22** [comment]
@Ajit-53 Are you still up on this issue?

**Comment by Ajit-53** [comment]
yaa i am working on this issues..since it is a part of  Hacktoberfest2020 . i will send a pr request between 1 to 31 october.

**Comment by Ajit-53** [comment]
please assign this issue to me..my code is almost ready.

**Comment by amritansh22** [comment]
@Ajit-53 It is already assigned
