### ISSUE TITLE
Find second maximum element in array 

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#58]

**Comment by gokulkannan7** [comment]
Hi, I would love to work on this!

**Comment by amritansh22** [comment]
@gokulkannan7 Yes sure. Make sure to follow all the points mentioned in contribution guidelines and open a PR once done.

**Comment by gokulkannan7** [comment]
since this is a part of hacktoberfest, shall I open a PR in the first week of October?

**Comment by amritansh22** [comment]
This is just for learning. It is to introduce how issues and Pull request work on github. So you can open PR right now also and later in October also.
