### ISSUE TITLE
Implement KMP algorithm 

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#61]

**Comment by Manoj13-coder** [comment]
i would like to contribute may i go ahead for this?

**Comment by Manoj13-coder** [comment]
May i start contribution from 1 october?

**Comment by amritansh22** [comment]
@Manoj13-coder You can start contributing right now

**Comment by Manoj13-coder** [comment]
May i start it from 1 October please?

**Comment by amritansh22** [comment]
I am daily adding more issues to work on. Right on these are just for understanding the workflow of Github. You can work right now to understand everything and come in October to work on some other issues

**Comment by Manoj13-coder** [comment]
ok great i will start working on it
