### ISSUE TITLE
Find median element of an array

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#62]

**Comment by d2Anubis** [comment]
I would like to work on this.

**Comment by amritansh22** [comment]
@d2Anubis Yes please go ahead.

**Comment by amritansh22** [comment]
@d2Anubis Are you still up on this issue?

**Comment by d2Anubis** [comment]
I did sent you a pull request after completion.

**Comment by d2Anubis** [comment]
It has been already merged this issue needs to be closed.

**Comment by amritansh22** [comment]
@d2Anubis Yes we have merged your PR. Sorry for bothering
