### ISSUE TITLE
RIght rotate an array k times

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#63]

**Comment by Maitryee-Choudhary** [comment]
i would like to work on this.Can you assign me?

**Comment by amritansh22** [comment]
@Maitryee-Choudhary You can work on this. Read the contribution guidelines and make sure to follow all points and open a PR once done.

**Comment by amritansh22** [comment]
@Maitryee-Choudhary I have assigned the issue to you please open PR once done

**Comment by Maitryee-Choudhary** [comment]
Ok thank you
