### ISSUE TITLE
Implement Queue using array

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#68]

**Comment by Uyadav207** [comment]
Hey @amritansh22 Kindly assign me the above issue.

Would love to work on this.

**Comment by amritansh22** [comment]
@Uyadav207 Yes you may start working on this issue, make sure to follow all the points mentioned in contribution guide and make a PR once done.

**Comment by amritansh22** [comment]
@Uyadav207 I have assigned the issue to you. Please open PR when done.
