### ISSUE TITLE
Implement Circular Queue using array

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#69]

**Comment by gayatri517** [comment]
I want to work on this issue please assign me.

**Comment by sanjeev2552** [comment]
I can do it please assign me.

**Comment by amritansh22** [comment]
@gayatri517 Done

**Comment by amritansh22** [comment]
@sanjeev2552 This issue is assigned to @gayatri517 You can look for some other open issues or create some of your own
