### ISSUE TITLE
Add a file code file written in C++ of selection sort 

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#7]
Add a file code file written in C++ of selection sort

**Comment by Jigyasa-Kumari** [comment]
Hey, can I work on this?

**Comment by amritansh22** [comment]
Yes please go ahead. Read the contribution guide and make sure to follow all the steps

**Comment by iaish-max** [comment]
I am a beginner in open source contribution , can i work on this.

**Comment by amritansh22** [comment]
@iaish-max This issue was already assigned to @Jigyasa-Kumari. You can work on some other issues.
