### ISSUE TITLE
Find Kth largest element in array

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#71]

**Comment by dolonmandal** [comment]
Please Assign.

**Comment by amritansh22** [comment]
@dolonmandal Yes you may start working on this issue, make sure to follow all the points mentioned in contribution guide and make a PR once done.

**Comment by nischalsoni** [comment]
@amritansh22 hey Amritansh, is there any issue which is not assigned to anyone, if yes, please assign it to me, I'd be happy to help :)

**Comment by amritansh22** [comment]
@nischalsoni There are few unassigned issues, in addition to them you can also create your own also

**Comment by anjali1102** [comment]
assign me

**Comment by amritansh22** [comment]
@anjali1102 done
