### ISSUE TITLE
Search an element in circular linked list

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#72]

**Comment by sukritidawar** [comment]
I want to work on this issue in cpp

**Comment by amritansh22** [comment]
@sukritidawar Yes you may start working on this issue, make sure to follow all the points mentioned in contribution guide and make a PR once done.

**Comment by sukritidawar** [comment]
> @sukritidawar Yes you may start working on this issue, make sure to follow all the points mentioned in contribution guide and make a PR once done.

Please assign the issue, so that there are no confusions and misconceptions in future.

**Comment by amritansh22** [comment]
@sukritidawar Done

**Comment by sukritidawar** [comment]
hi @amritansh22 , please review this:
https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/pull/172
