### ISSUE TITLE
Find duplicate elements in circular linked list

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#75]

**Comment by Bijoy-007** [comment]
Please tell me about the language to use here.
Is it C++?
If C++ can I do this one?

**Comment by Bijoy-007** [comment]
Hi can I do this?

**Comment by amritansh22** [comment]
Yes sure @Bijoy-007 Open a PR once done

**Comment by amritansh22** [comment]
I have assigned you @Bijoy-007

**Comment by kritika122000** [comment]
assign me please

**Comment by amritansh22** [comment]
@kritika122000 This issue is already assigned. You may look for some other or open your own issues here
