### ISSUE TITLE
Implement queue using two stacks

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#77]

**Comment by gayatri517** [comment]
I would like to work on this issue please assign me.

**Comment by amritansh22** [comment]
@gayatri517 Yes you may start working on this issue, make sure to follow all the points mentioned in contribution guide and make a PR once done.

**Comment by pranav2012** [comment]
hey @amritansh22  can i work on this

**Comment by amritansh22** [comment]
Excellent work @pranav2012 thanks a lot for opening this PR
