### ISSUE TITLE
Find only repeated number in an array

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#86]

**Comment by ishi0301** [comment]
Please assign me.

**Comment by amritansh22** [comment]
@ishi0301 Since there are limited number of issues and you are working on already this issue, so please complete this one and then I would assign you to other issues

**Comment by ishi0301** [comment]
Okay.

**Comment by anjali1102** [comment]
assign me

**Comment by amritansh22** [comment]
Done

**Comment by ishi0301** [comment]
@amritansh22 . In the above message you told me to complete this issue. Now you have assigned it to someone else.

**Comment by amritansh22** [comment]
@ishi0301 I am extremely sorry. I did this by mistake. Was confused between the Issue numbers

**Comment by amritansh22** [comment]
@ishi0301 I have assigned you

**Comment by ishi0301** [comment]
@amritansh22 No problem . Thank you.
