### ISSUE TITLE
Print the middle element of a singly linked list

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#87]

**Comment by ishi0301** [comment]
Please assign me.

**Comment by amitsaini4556** [comment]
I'll work on this issue, please assign it to me.

**Comment by hemabhagnani** [comment]
I would like to work on this issue. Please assign it to me. Thank You

**Comment by Ajit-53** [comment]
I would like to add the code for Print the middle element of a singly linked list.using slow and fast pointer.
Please assign it to me.

**Comment by mayureshkate** [comment]
I'll complete it assign me

**Comment by amritansh22** [comment]
@hemabhagnani Done

**Comment by kritika122000** [comment]
can you please assign me

**Comment by amritansh22** [comment]
@kritika122000 This issue is already assigned. You may look for some other or open your own issues here
