### ISSUE TITLE
Print Nth node from end in singly linked list

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#88]

**Comment by mahimagoyalx** [comment]
Please assign me this issue.

**Comment by gayatri517** [comment]
I want work on this issue please assign it to me. I will put a PR on 1st october.

**Comment by Ajit-53** [comment]
i would like to work on this.Can please you assign me.because i know to solve this question using 3 different approaches.

**Comment by amritansh22** [comment]
@gayatri517 I will open more issues till 1st October, I will assign you to them

**Comment by amritansh22** [comment]
@Ajit-53 Done. And do the most optimized one only
