### ISSUE TITLE
Check if a number is palindrome

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#89]

**Comment by ishi0301** [comment]
Please assign me.

**Comment by Tushar11Raj** [comment]
Can i do this?

**Comment by amritansh22** [comment]
Since @ishi0301 asked first, I am going to assign it to her, you may look for other issues or open your own

**Comment by amritansh22** [comment]
@ishi0301 Make sure to follow all the points of the contribution guide and make a PR once done

**Comment by ishi0301** [comment]
Okay sure.

**Comment by shyamaldeepak** [comment]
#include <iostream>
using namespace std;

int main()
{
     int n, num, digit, rev = 0;

     cout << "Enter a positive number: ";
     cin >> num;

     n = num;

     do
     {
         digit = num % 10;
         rev = (rev * 10) + digit;
         num = num / 10;
     } while (num != 0);

     cout << " The reverse of the number is: " << rev << endl;

     if (n == rev)
         cout << " The number is a palindrome.";
     else
         cout << " The number is not a palindrome.";

    return 0;
}

**Comment by ishi0301** [comment]
@shyamaldeepak I am assigned this issue. Kindly delete your code.

**Comment by kritika122000** [comment]
can you assign me please!!

**Comment by amritansh22** [comment]
@kritika122000 This issue is already assigned. You may look for some other or open your own issues here
