### ISSUE TITLE
Find frequency of a given number in a singly linked list

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#91]

**Comment by Tushar11Raj** [comment]
Can I do this?

**Comment by amritansh22** [comment]
@Tushar11Raj Done
Make sure to follow all the points of the contribution guide and make a PR once done

**Comment by Tushar11Raj** [comment]
Since this issue is labeled under the Hactoberfest I will make the PR once the event starts :-)

**Comment by amritansh22** [comment]
@Tushar11Raj I will add more issues during hactoberfest. You can do this now also.

**Comment by piyush9311** [comment]
May I work on this

**Comment by amritansh22** [comment]
@piyush9311 Done. Please open a PR once done
