### ISSUE TITLE
Detect loop in a singly linked list

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#92]

**Comment by ankitksh81** [comment]
Hey @amritansh22 let me know if I can work on this one.

**Comment by amritansh22** [comment]
@ankitksh81 assigned.

**Comment by kritika122000** [comment]
assign me please

**Comment by amritansh22** [comment]
@kritika122000 This issue is already assigned. You may look for some other or open your own issues here

**Comment by ankitksh81** [comment]
Hi @amritansh22, Can I work on a new branch for this issue ?

**Comment by amritansh22** [comment]
@ankitksh81 I didn't get you. Can you please elaborate.

**Comment by ankitksh81** [comment]
I already have the code for another issue in my master and if I add the code for this issue also then while creating the PR, both of the issues will come in one PR. So, I want to create a new branch to solve this issue. Will that be fine ?

**Comment by amritansh22** [comment]
Yes absolutely. It will be fine.

**Comment by ankitksh81** [comment]
@chaturvediabhay24 I'm already assigned on this issue. You should atleast ask for the owner's permission before creating a PR.
And if you are doing it for hacktoberfest then let me tell you that this PR will not be counted as you have created it before 1st oct.
@amritansh22 please take a look at this.
