### ISSUE TITLE
Remove duplicates from a singly linked list

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#93]

**Comment by ishi0301** [comment]
Please assign me.

**Comment by mahimagoyalx** [comment]
Please assign me this issue.

**Comment by anjali1102** [comment]
assign me

**Comment by amritansh22** [comment]
@anjali1102 Due to limited number of issues to work upon I am assigning one issue at a time and I see you are already assigned to one open issue.

**Comment by mayureshkate** [comment]
assign me

**Comment by amritansh22** [comment]
@mayureshkate Done

**Comment by Pratap2018** [comment]
assign me

**Comment by amritansh22** [comment]
@Pratap2018 This issue is already assigned. You may look for other issues or open your own here.
