### ISSUE TITLE
Equal sum partition dynamic programming

### ISSUE THREAD

**Issue by Bijoy-007** [amritansh22/Data-Structures-and-Algorithms-in-cpp#95]
Can I do this?

**Comment by amritansh22** [comment]
Yes sure. I have assigned it you.

**Comment by Ankitlenka26** [comment]
Can I work on this ?

**Comment by amritansh22** [comment]
@Ankitlenka26 Since this issue is already assigned, you may look for other issues or open your own here

**Comment by Bijoy-007** [comment]
Please review and inform me if some is missing or needs to be changed
